layout_spectrum: 0.6230307666119188
typography_spectrum: 0.1922448428813368
color:
  brandStrength: 0.08236217661760747
  lightness: 0.8537700902670622
  saturation: 0.3112325230613351
  rhythmicContrast: 0.5001490474678576
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
analytics:
  google: UA-37934539-1
  facebook: '982448711860630'
author:
  name: Narq.net
  url: 'http://narq.net'
  email: ian SPLAT narq.net
name: Narq.net
navigation:
  - name: Music
    url: 'https://soundcloud.com/narq'
    type: external
  - name: Dog Photography
    url: 'http://dogstarphoto.co.uk'
    type: external
  - name: Photography
    url: 'https://SiriusPhoto.net'
    type: external
title: Ian Morrison's Narq.net
description: 'Reviews, Videos, Click-Bait, and Awesome Opinions.'
purpose:
  - type: external
    url: 'https://facebook.com/narq.net'
    label: Like on Facebook
  - type: external
    url: 'https://twitter.com/narq'
    label: Follow on Twitter
